import "./globals.css";

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body className="bg-gray-800 min-h-screen px-4 py-12">
				<div className="mx-auto w-full max-w-6xl px-4 text-white">
					{children}
				</div>
			</body>
		</html>
	);
}
